#!/bin/bash

set -eu

GIT_TAG=$( git describe --tags || echo "devel" )
GIT_COMMIT=$( git log -1 --format="%H" )

cat << EOF
/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2023 The Kubernetes Authors.
 */

/* THIS FILE IS AUTOGENERATED - DO NOT EDIT */

package version

const (
	GitCommit = "${GIT_COMMIT}"
	GitVersion = "${GIT_TAG}"
)
EOF
